<?php

namespace Database\Seeders;

use App\Models\umkmModel;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class umkmSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        umkmModel::create([
            'User_id' => 1,
            'Nama_umkm' => 'UMKM 1',
            'pemilik' => 'John Doe',
            'alamat' => '123 Main Street',
            'NIB' => 123456789,
            'NPWP' => 987654321,
            'waktu_berdiri' => now(),
            'jenis' => 'Makanan Olahan',
            'Pirt' => 987,
            'bpom' => 654,
            'halal' => 321,
            'merek' => 111,
            'hak_cipta' => 222,
            'no1' => 333,
            'no2' => 444,
            'email' => 'umkm1@example.com',
            'website' => 'http://umkm1.com',
            'fb' => 'umkm1_facebook',
            'ig' => 'umkm1_instagram',
            'tokped' => 'umkm1_tokopedia',
            'shopee' => 'umkm1_shopee',
            'bukalapak' => 'umkm1_bukalapak',
            'Asset' => 1000000,
            'omset' => 500000,
            'tenagaL' => 5,
            'tenagaP' => 3,
            'desa' => 'Village 1',
            'kab' => 'District 1',
            'prov' => 'Province 1',
            'nas' => 'National 1',
            'exp' => 'Export 1',
            'kapasitas' => 'High',
            'status' => 'Active',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        umkmModel::create([
            'User_id' => 2,
            'Nama_umkm' => 'UMKM 2',
            'pemilik' => 'Jane Smith',
            'alamat' => '456 Oak Street',
            'NIB' => 987654321,
            'NPWP' => 123456789,
            'waktu_berdiri' => now(),
            'jenis' => 'Pertanian',
            'Pirt' => 123,
            'bpom' => 456,
            'halal' => 789,
            'merek' => 222,
            'hak_cipta' => 333,
            'no1' => 444,
            'no2' => 555,
            'email' => 'umkm2@example.com',
            'website' => 'http://umkm2.com',
            'fb' => 'umkm2_facebook',
            'ig' => 'umkm2_instagram',
            'tokped' => 'umkm2_tokopedia',
            'shopee' => 'umkm2_shopee',
            'bukalapak' => 'umkm2_bukalapak',
            'Asset' => 800000,
            'omset' => 300000,
            'tenagaL' => 4,
            'tenagaP' => 2,
            'desa' => 'Village 2',
            'kab' => 'District 2',
            'prov' => 'Province 2',
            'nas' => 'National 2',
            'exp' => 'Export 2',
            'kapasitas' => 'Medium',
            'status' => 'Inactive',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        umkmModel::create([
            'User_id' => 3,
            'Nama_umkm' => 'UMKM 3',
            'pemilik' => 'Jane Smith',
            'alamat' => '4567 Oak Street',
            'NIB' => 987654321,
            'NPWP' => 123456789,
            'waktu_berdiri' => now(),
            'jenis' => 'Peternakan',
            'Pirt' => 123,
            'bpom' => 456,
            'halal' => 789,
            'merek' => 222,
            'hak_cipta' => 333,
            'no1' => 444,
            'no2' => 555,
            'email' => 'umkm2@example.com',
            'website' => 'http://umkm2.com',
            'fb' => 'umkm2_facebook',
            'ig' => 'umkm2_instagram',
            'tokped' => 'umkm2_tokopedia',
            'shopee' => 'umkm2_shopee',
            'bukalapak' => 'umkm2_bukalapak',
            'Asset' => 800000,
            'omset' => 300000,
            'tenagaL' => 4,
            'tenagaP' => 2,
            'desa' => 'Village 3',
            'kab' => 'District 3',
            'prov' => 'Province 3',
            'nas' => 'National 3',
            'exp' => 'Export 3',
            'kapasitas' => 'Medium',
            'status' => 'Inactive',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }
}
